name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

      
jobs:

  build:

    runs-on: self-hosted 

    steps:
    - name: Pull docker image
      run: sudo docker pull lukaneek/cicd-pipeline:latest
    - name: Delete old docker container
      run: sudo docker rm -f cicd-pipeline || true
    - name: Run docker container
      run: sudo docker run -d -p 80:80 --name cicd-pipeline lukaneek/cicd-pipeline
      