name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub 
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t cicd-pipeline .
    - name: tag the Docker image
      run: docker tag cicd-pipeline:latest lukaneek/cicd-pipelinelatest
    - name: list the Docker images
      run: docker image ls -a
    - name: Push to Dockerhub
      run: docker push lukaneek/cicd-pipeline:latest
